# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eeW-Hg2G2E3UYYbPYe2VQyrkNft-KtUa
"""

def tashxis(belgi):
  if belgi == "isitma":
   return "Parasetamol iching"
  elif belgi == " bosh og'riq ":
      return "tirimol iching"
  elif belgi == "Tish og'riq":
      return "Quepen iching"
  elif belgi == " Asab tizimi kasalliklari":
      return "Sertralin iching"
  elif belgi == "Allergik kasalliklar ":
      return "Loratadin iching"
  elif belgi == "Jigar kasalliklari":
      return "Furosemid iching"
  elif belgi == "vazn ortishi kasaligi ":
      return "Diyet va jismoniy mashqlar qiling"
  elif belgi == "Psixiatrik kasalliklar":
      return "Sertralin, Paroksetin iching"
  elif belgi == "Gastrit va oshqozon yarasi":
      return "Omeprazol iching"
  else:
       return "shifokorga murojiat qiling"
belgi=input(" Kasalik belgisini kiriting ")
natija=tashxis(belgi)
print(natija)

from google.colab.patches import cv2_imshow
import cv2
def telefon(belgi):
  if belgi == "markaziy hujumchi":
   rasm=cv2.imread("eldor1.webp")
   cv2_imshow(rasm)
   return " Eldor Shomurodov"
  elif belgi == "o'ng qanot hujumchi":
   rasm=cv2.imread("jalol5.webp")
   cv2_imshow(rasm)
   return "Jaloliddin Masharipov"
  elif belgi == "chap qanot hujumchi":
    rasm=cv2.imread("abbos3.webp")
    cv2_imshow(rasm)
    return "Abbos Fayzullayev"
  elif belgi == "hujumchikor yarim himoyachi":
    rasm=cv2.imread("doston4.webp")
    cv2_imshow(rasm)
    return "Doston Urunov"
  elif belgi == "yarim1 himoyachi":
     rasm=cv2.imread("shukurov10.webp")
     cv2_imshow(rasm)
     return "Otabek Shukurov"
  elif belgi == "yarim2 himoyachi":
     rasm=cv2.imread("hamrabekov11.webp")
     cv2_imshow(rasm)
     return "Odiljon Hamrabekov"
  elif belgi == "markaziy1 himoyachi":
     rasm=cv2.imread("rustam6.webp")
     cv2_imshow(rasm)
     return "Rustam Ashurmatov"
  elif belgi == "markaziy2 himoyachi":
     rasm=cv2.imread("husanov6.webp")
     cv2_imshow(rasm)
     return "Abduqodir Husanov"
  elif belgi == "chap qanot himoyachi":
     rasm=cv2.imread("sherzod7.webp")
     cv2_imshow(rasm)
     return "Sherzod Nasrullayev"
  elif belgi == "o'ng qanot himoyachi":
     rasm=cv2.imread("alijonov8.webp")
     cv2_imshow(rasm)
     return "Hojiakbar Alijonov"
  elif belgi == "varatabon":
     rasm=cv2.imread("otkir9.webp")
     cv2_imshow(rasm)
     return "O'tkir Yusupov"
  else:
     return "Murabbiyga murojat qiling"
belgi=input(" Qaysi pazitsiyada o'yinchi kerak ")
natija=telefon(belgi)
print(natija)